name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build x64
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /c /MT src\binn.c
        lib binn.obj
        dir
        if not exist static mkdir static
        move /y binn.lib static\
        cl /MT /D_USRDLL /D_WINDLL src\binn.c src\win32\dllmain.c /LD /Febinn-3.0.dll /link /DEF:src\win32\binn.def
        dir
        dumpbin /dependents binn-3.0.dll
        mkdir x64
        move static x64\
        move binn-3.0.dll x64\
        move binn-3.0.lib x64\

    - name: build win32
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        cl /c /MT src\binn.c
        lib binn.obj
        dir
        if not exist static mkdir static
        move /y binn.lib static\
        cl /MT /D_USRDLL /D_WINDLL src\binn.c src\win32\dllmain.c /LD /Febinn-3.0.dll /link /DEF:src\win32\binn.def
        dir
        dumpbin /dependents binn-3.0.dll
        mkdir win32
        move static win32\
        move binn-3.0.dll win32\
        move binn-3.0.lib win32\

    - name: list files
      shell: cmd
      run: |
        dir x64
        dir win32
        dir x64\static
        dir win32\static

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binn-windows
        path: |
          x64
          win32
