name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /c src\binn.c
        lib binn.obj
        dir
        cl /LD src\binn.c src\win32\dllmain.c /DEF:src\win32\binn.def /link /DLL /OUT:binn-3.0.dll
        dir
