name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build x64
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /c /MT src\binn.c
        lib binn.obj
        dir
        if not exist static mkdir static
        move /y libbinn.lib static\
        cl /MT /D_USRDLL /D_WINDLL src\binn.c src\win32\dllmain.c /LD /Febinn-3.0.dll /link /DEF:src\win32\binn.def
        dir
        dumpbin /dependents binn-3.0.dll

    - name: zip x64 artifacts
      run: |
        Get-ChildItem -Path static, binn-3.0.dll, binn-3.0.lib | Compress-Archive -DestinationPath binn-windows-x64.zip

    - name: build win32
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        cl /c /MT src\binn.c
        lib binn.obj
        dir
        if not exist static mkdir static
        move /y libbinn.lib static\
        cl /MT /D_USRDLL /D_WINDLL src\binn.c src\win32\dllmain.c /LD /Febinn-3.0.dll /link /DEF:src\win32\binn.def
        dir
        dumpbin /dependents binn-3.0.dll

    - name: zip win32 artifacts
      run: |
        Get-ChildItem -Path static, binn-3.0.dll, binn-3.0.lib | Compress-Archive -DestinationPath binn-windows-win32.zip

    - name: list files
      shell: cmd
      run: dir

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          binn-windows-x64.zip
          binn-windows-win32.zip
